# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/stretchr/testify
%global goipath         github.com/stretchr/testify
Version:                1.7.0

%gometa

%global common_description %{expand:
A toolkit with common assertions and mocks that plays nicely with the standard
library.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md MAINTAINERS.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A toolkit with common assertions and mocks that plays nicely with the standard library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in _codegen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.md MAINTAINERS.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
