# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/go-yaml/yaml
%global goipath         github.com/go-yaml/yaml
Version:                2.4.0

%gometa

%global common_description %{expand:
YAML support for the Go language.}

%global golicenses      LICENSE LICENSE.libyaml NOTICE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        YAML support for the Go language

# Upstream license specification: MIT and Apache-2.0
License:        MIT and ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
