# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/go-check/check
%global goipath         github.com/go-check/check
%global commit          10cb98267c6cb43ea9cd6793f29ff4089c306974

%gometa

%global common_description %{expand:
Rich testing for the Go language.}

%global golicenses      LICENSE
%global godocs          README.md TODO

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Rich testing for the Go language

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
