# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/ernesto-jimenez/gogen
%global goipath         github.com/ernesto-jimenez/gogen
%global commit          d7d4131e6607813977e78297a6060f360f056a97

%gometa

%global common_description %{expand:
A set of go packages and command line tools to generate Go code.}

%global golicenses      LICENSE
%global godocs          cmd/goautomock/README.md\\\
                        cmd/goexportdefault/README.md\\\
                        cmd/gosimplemock/README.md cmd/gospecific/README.md\\\
                        cmd/gounmarshalmap/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        A set of go packages and command line tools to generate Go code

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc cmd/goautomock/README.md cmd/goexportdefault/README.md
%doc cmd/gosimplemock/README.md cmd/gospecific/README.md
%doc cmd/gounmarshalmap/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
