# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/stretchr/objx
%global goipath         github.com/stretchr/objx
Version:                0.3.0

%gometa

%global common_description %{expand:
Go package for dealing with maps, slices, JSON and other data.}

%global golicenses      LICENSE
%global godocs          README.md codegen/array-access.txt\\\
                        codegen/template.txt codegen/template_test.txt\\\
                        codegen/types_list.txt

Name:           %{goname}
Release:        %autorelease
Summary:        Go package for dealing with maps, slices, JSON and other data

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
