# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://gopkg.in/yaml.v3
%global goipath         gopkg.in/yaml.v3
%global forgeurl        github.com/go-yaml/yaml
Version:                2.4.0
%global commit          496545a6307b2a7d7a710fd516e5e16e8ab62dbc

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE NOTICE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
